[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openairbearing"
dynamic = ["version"]
description = "A Python package for externally pressurized air bearing analysis."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Mikael Miettinen", email = "mikael.miettinen@iki.fi" },
]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dash>=2.18.2,<3.0.0",
    "numpy>=2.2.3,<3.0.0",
    "plotly>=6.0.0,<7.0.0",
    "scipy>=1.7.0,<2.0.0",
]

[project.urls]
Homepage = "https://github.com/Aalto-Arotor/openAirBearing"
"Online demo" = "https://www.openairbearing.com"

[project.scripts]
openairbearing = "openairbearing.app.app:main"

# --- Setuptools specific configuration ---
[tool.setuptools.packages.find]
exclude = ["examples*", "tests*"]

[tool.setuptools.dynamic]
version = {attr = "openairbearing.__version__"}

[tool.setuptools.package-data]
openairbearing = ["assets/style.css", "assets/favicon.ico"]
[tool.ruff]
indent-width = 4
line-length = 88
